### PR TITLE
add aliyun storeclass yaml file

### PR DESCRIPTION
**Pull request by walt-liuzw**
remove other unecessary files

### CODE REVIEW

**Comment by jwulf** [comment]
Hi @walt-liuzw, you have committed the change using the name liuzhiwei.

Can you amend the commit to use your GitHub account email, or add liuzhiwei to your GitHub account: and sign the digital Contributor License Agreement. We need this to merge the patch.

**Comment by walt-liuzw** [comment]
@jwulf hi,i have add liuzhiwei to my github profile name

**Comment by walt-liuzw** [comment]
@jwulf  this is my first time  use CLA, It's a problem for me.⊙﹏⊙b

**Comment by walt-liuzw** [comment]
@jwulf ,sorry,i update my profile name is invalid,  github account username can not be updated by liuzhiwei, CLA FullName has not edit entry, i will give up....

**Pull request closed without merging**
